theme: jekyll-theme-minimal
title: Pass The Cheese -- An Experiment with AI-driven development
description: This is an experiment.  Can I build a production-ready web-based game using only AI? This blog will chronicle my journey
